{% set name = "aws-c-event-stream" %}
{% set version = "0.2.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 310ca617f713bf664e4c7485a3d42c1fb57813abd0107e49790d107def7cde4f

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("aws-c-event-stream", max_pin="x.x.x") }}

requirements:
  build:
    - cmake !=3.19.0,!=3.19.1
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
  host:
    - aws-c-common
    - aws-c-io
    - aws-checksums

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-event-stream${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/event-stream/event_stream.h  # [unix]

about:
  home: https://github.com/awslabs/aws-c-event-stream
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C99 implementation of the vnd.amazon.eventstream content-type.

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
